import { useState } from 'react'
import { CheckCircle2, ClipboardList, Mail, Package, Send, UserRound } from 'lucide-react'

const initial = { name: '', company: '', pickup: '', delivery: '', pickupDate: '', freightType: '', pallets: '', weight: '', dimensions: '', email: '', phone: '', notes: '' }

export default function Booking() {
  const [form, setForm] = useState(initial)
  const [status, setStatus] = useState('')
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const submit = (event) => { event.preventDefault(); setStatus('success'); setForm(initial) }
  const field = (label, name, type = 'text', options = {}) => <div className={`field ${options.full ? 'field--full' : ''}`}><label htmlFor={name}>{label}</label>{options.select ? <select id={name} name={name} value={form[name]} onChange={update}><option value="">Select freight type</option><option>Full Truckload (FTL)</option><option>Less Than Truckload (LTL)</option><option>Pallet freight</option><option>Same-day local delivery</option></select> : <input id={name} name={name} type={type} value={form[name]} onChange={update} required={options.required} placeholder={options.placeholder} />}</div>
  return <section className="section section--soft"><div className="container form-shell"><div><span className="eyebrow">Start a conversation</span><h1 className="section-title">Tell us what needs moving.</h1><p className="section-copy">Give our dispatch team the details and we’ll get back to you with a practical freight quote.</p><ul className="feature-list"><li><CheckCircle2 size={18} /> No obligation, clear next steps</li><li><CheckCircle2 size={18} /> Pickup planning around your schedule</li><li><CheckCircle2 size={18} /> Direct support from a real freight team</li></ul><a className="contact-detail" href="mailto:info@a11freight.com"><Mail size={18} /> info@a11freight.com</a></div><form className="form-card" onSubmit={submit}><h3>Request a freight quote</h3><p>Fields marked with an asterisk help us quote accurately.</p><div className="form-section-title"><ClipboardList size={15} /> Shipment</div><div className="form-grid">{field('Pickup location *', 'pickup', 'text', { required: true, placeholder: 'City or postal code' })}{field('Delivery location *', 'delivery', 'text', { required: true, placeholder: 'City or postal code' })}{field('Pickup date', 'pickupDate', 'date')}{field('Freight type', 'freightType', 'text', { select: true })}{field('Pallets / pieces', 'pallets', 'number', { placeholder: 'e.g. 12' })}{field('Weight (lb)', 'weight', 'number', { placeholder: 'Approximate weight' })}{field('Dimensions', 'dimensions', 'text', { full: true, placeholder: 'Length x width x height' })}</div><div className="form-section-title"><UserRound size={15} /> Customer</div><div className="form-grid">{field('Contact name *', 'name', 'text', { required: true })}{field('Company name', 'company')}{field('Phone *', 'phone', 'tel', { required: true })}{field('Email *', 'email', 'email', { required: true })}</div><div className="form-section-title"><Package size={15} /> Notes</div><div className="form-grid"><div className="field field--full"><label htmlFor="notes">Additional details</label><textarea id="notes" name="notes" value={form.notes} onChange={update} placeholder="Anything our dispatch team should know?" /></div></div><button className="btn btn-primary form-submit" type="submit"><Send size={15} /> Send quote request</button>{status === 'success' && <p className="form-status success">Thanks. Your request is ready for the dispatch team. We’ll be in touch shortly.</p>}</form></div></section>
}
