/* global process */
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
const clean = (value, max = 500) => String(value || '').trim().slice(0, max)
const escapeHtml = (value) => clean(value, 5000).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char])
const emailRows = (items) => items.map(([label, value], index) => `<tr><td style="width:38%;padding:13px 16px;border-bottom:${index === items.length - 1 ? '0' : '1px solid #e8edf2'};color:#667085;font-size:13px;font-weight:700;vertical-align:top">${escapeHtml(label)}</td><td style="padding:13px 16px;border-bottom:${index === items.length - 1 ? '0' : '1px solid #e8edf2'};color:#17212b;font-size:14px;font-weight:600;line-height:1.5;white-space:pre-wrap;vertical-align:top">${escapeHtml(value)}</td></tr>`).join('')
const section = (title, items) => `<h2 style="margin:0 0 10px;color:#1f2933;font-size:15px">${title}</h2><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-bottom:24px;border:1px solid #e8edf2;border-radius:10px;border-collapse:separate;overflow:hidden">${emailRows(items)}</table>`
const emailTemplate = ({ name, company, email, phone, shipment, notes }) => `<!doctype html><html><body style="margin:0;padding:0;background:#f3f5f7;font-family:Arial,Helvetica,sans-serif;color:#17212b"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f3f5f7"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 8px 30px rgba(23,33,43,.10)"><tr><td style="padding:30px 34px;background:#1f2933;border-bottom:5px solid #bc7049"><div style="color:#efb08f;font-size:11px;font-weight:800;letter-spacing:2.2px;text-transform:uppercase">A11 Freight</div><h1 style="margin:8px 0 6px;color:#fff;font-size:26px">New quote request</h1><p style="margin:0;color:#d5dce3;font-size:14px">A new shipment enquiry is ready for review.</p></td></tr><tr><td style="padding:28px 30px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-bottom:22px"><tr><td style="padding:18px 20px;background:#fff4ee;border-left:4px solid #bc7049;border-radius:8px"><div style="color:#9a5230;font-size:11px;font-weight:800;letter-spacing:1.5px;text-transform:uppercase">Route</div><div style="margin-top:6px;color:#17212b;font-size:18px;font-weight:800">${escapeHtml(shipment[0][1])} <span style="color:#bc7049">&rarr;</span> ${escapeHtml(shipment[1][1])}</div></td></tr></table>${section('Customer details', [['Name', name], ['Company', company], ['Email', email], ['Phone', phone]])}${section('Shipment details', shipment)}<h2 style="margin:0 0 10px;color:#1f2933;font-size:15px">Additional notes</h2><div style="padding:16px;background:#f7f9fb;border:1px solid #e8edf2;border-radius:10px;color:#344054;font-size:14px;line-height:1.6;white-space:pre-wrap">${escapeHtml(notes)}</div><table role="presentation" cellspacing="0" cellpadding="0" style="margin-top:26px"><tr><td style="border-radius:8px;background:#bc7049"><a href="mailto:${escapeHtml(email)}" style="display:inline-block;padding:13px 22px;color:#fff;text-decoration:none;font-size:14px;font-weight:800">Reply to ${escapeHtml(name)}</a></td></tr></table></td></tr><tr><td style="padding:18px 30px;background:#1f2933;color:#aeb8c2;font-size:11px">Submitted through the A11 Freight website quote form.</td></tr></table></td></tr></table></body></html>`

export default async function handler(request, response) {
  if (request.method !== 'POST') { response.setHeader('Allow', 'POST'); return response.status(405).json({ error: 'Method not allowed.' }) }
  try {
    const origins = String(process.env.QUOTE_ALLOWED_ORIGINS || '').split(',').map((value) => value.trim()).filter(Boolean)
    const origin = request.headers?.origin
    if (origins.length && origin && !origins.includes(origin)) return response.status(403).json({ error: 'This website is not allowed to submit quote requests.' })
    const body = typeof request.body === 'string' ? JSON.parse(request.body) : (request.body || {})
    if (clean(body.website)) return response.status(200).json({ ok: true })
    const name = clean(body.name, 120), email = clean(body.email, 254).toLowerCase(), phone = clean(body.phone, 60), pickup = clean(body.pickup, 180), delivery = clean(body.delivery, 180)
    if (!name || !phone || !pickup || !delivery || !EMAIL_PATTERN.test(email)) return response.status(400).json({ error: 'Please complete all required fields with a valid email address.' })
    const apiKey = process.env.RESEND_API_KEY, fromEmail = clean(process.env.RESEND_FROM_EMAIL, 254), recipient = clean(process.env.QUOTE_RECIPIENT_EMAIL || fromEmail, 254), fromName = clean(process.env.RESEND_FROM_NAME || 'A11 Freight', 100)
    if (!apiKey || !EMAIL_PATTERN.test(fromEmail) || !EMAIL_PATTERN.test(recipient)) throw new Error('Resend is not configured.')
    const company = clean(body.company, 160) || 'Not provided'
    const shipment = [['Pickup', pickup], ['Delivery', delivery], ['Pickup date', clean(body.pickupDate, 30) || 'Not provided'], ['Freight type', clean(body.freightType, 80) || 'Not specified'], ['Pallets / pieces', clean(body.pallets, 30) || 'Not provided'], ['Weight (lb)', clean(body.weight, 30) || 'Not provided'], ['Dimensions', clean(body.dimensions, 160) || 'Not provided']]
    const html = emailTemplate({ name, company, email, phone, shipment, notes: clean(body.notes, 3000) || 'None' })
    const resendResponse = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ from: `${fromName} <${fromEmail}>`, to: [recipient], reply_to: email, subject: `New freight quote request — ${pickup} to ${delivery}`, html }) })
    if (!resendResponse.ok) { console.error('Resend email failed:', resendResponse.status, await resendResponse.text()); throw new Error('The email service rejected the request.') }
    const result = await resendResponse.json()
    return response.status(200).json({ ok: true, id: result.id })
  } catch (error) {
    console.error('Quote submission failed:', error)
    return response.status(500).json({ error: 'We could not send your request. Please try again or email info@a11freight.com.' })
  }
}
